### ISSUE TITLE
New version of gfwx on gfwx.org.

### ISSUE THREAD

**Issue by grahamfyffe** [c0nk/gfwx#1]
There's a new version of the gfwx code on gfwx.org which fixes some potential security issues: http://gfwx.org/gfwx.h

Could be good to integrate the new code into this project!

**Comment by c0nk** [comment]
Thanks for the heads up. I will try to merge your changes soon.

**Comment by c0nk** [comment]
I have merged in your changes. I ran the new code on my corpus of over 200,000 images and the results were all bit identical to the last version. So I *think* the changes are ok.
